#pragma once

#include <cstdint>

namespace I2c
{

enum class Tsl2561InterruptPersistenceLevel : uint8_t
{
		EVERY_CYCLE = 0,
		EVERY_CYCLE_OUT_OF_RANGE = 1,
		EVERY_2_CYCLES_OUT_OF_RANGE = 2,
		EVERY_3_CYCLES_OUT_OF_RANGE = 3,
		EVERY_4_CYCLES_OUT_OF_RANGE = 4,
		EVERY_5_CYCLES_OUT_OF_RANGE = 5,
		EVERY_6_CYCLES_OUT_OF_RANGE = 6,
		EVERY_7_CYCLES_OUT_OF_RANGE = 7,
		EVERY_8_CYCLES_OUT_OF_RANGE = 8,
		EVERY_9_CYCLES_OUT_OF_RANGE = 9,
		EVERY_10_CYCLES_OUT_OF_RANGE = 10,
		EVERY_11_CYCLES_OUT_OF_RANGE = 11,
		EVERY_12_CYCLES_OUT_OF_RANGE = 12,
		EVERY_13_CYCLES_OUT_OF_RANGE = 13,
		EVERY_14_CYCLES_OUT_OF_RANGE = 14,
		EVERY_15_CYCLES_OUT_OF_RANGE = 15,
};

} // namespace I2c
